# Basic
title: Miracle Lee
subtitle: Be confident, not arrogant.
welcome_message: <a href="https://github.com/lixymiracle/lixymiracle.github.io" target="_blank">Welcome to Miracle's blog.</a>
description: Life never stops pushing forward. Stay focused and never slow down with regrets.
creator: <a href="http://lixiangyu.cc">@Miracle</a>

url: "http://lixiangyu.cc"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: orange

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: Encelade
    github: lixymiracle
    mail: lixymiracle@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
